name: Frontend Pipeline

on:
  push:
    branches: [ "frontend" ]
  pull_request:
    branches: [ "frontend" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install HTML and CSS linters
        run: |
          sudo apt-get install -y npm
          npm install --global htmlhint stylelint

      - name: Lint HTML files
        run: htmlhint "**/*.html"

      - name: Lint CSS files
        run: stylelint "**/*.css"